spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: provided-via-env-variable
    #username: provided-via-env-variable
    #password: provided-via-env-variable
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:fake-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:fake-client-secret}
